force-app/main/default/objects/Game__c/Game__c.object-meta.xml
<CustomObject>
    <description>Game in totalizator.</description>
    <label>Game</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Game__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hourses</fullName>
            </value>
            <value>
                <fullName>Bullfights</fullName>
            </value>
            <value>
                <fullName>Cars</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UtilsTest.cls
@isTest
public class UtilsTest {
    @isTest 
    static void groupRecordsByFieldTest(){
        List<Game__c> games = TestDataFactory.createGames(4);
        
        Test.startTest();
        Map<String, List<SObject>> groupedRecordsByField = Utils.groupRecordsByField(games, 'Type__c');
        Test.stopTest();
        
        System.assert(groupedRecordsByField.keySet().size() > 0, 'Method should populate the map');
        System.assert(groupedRecordsByField.containsKey('Cars'), 'Method should use the Type__c value');
        System.assertEquals(groupedRecordsByField.get('Cars').size(),4);
    }
    
    @isTest 
    static void filterRecordsTest(){
        List<Game__c> games = TestDataFactory.createGames(4);
        
        
        Test.startTest();
        List<SObject> filteredRecords = Utils.filterRecords(games, 'Type__c', new Set<String>{'Cars'});
        Test.stopTest();
        
        System.assert(filteredRecords.size()>0, 'List has to be populated');

    }
    @isTest 
    static void filterRecordsEmptyTest(){
        List<Game__c> games = TestDataFactory.createGames(4);
        
        
        Test.startTest();
        List<SObject> filteredRecords = Utils.filterRecords(games, 'Type__c', new Set<String>{'Hourses'});
        Test.stopTest();
        
        System.assert(filteredRecords.isEmpty(), 'List has to be empty');

    }
}