force-app/main/default/objects/Game__c/Game__c.object-meta.xml
<CustomObject>
    <description>Game in totalizator.</description>
    <label>Game</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Game__c/fields/Game_Rating__c.field-meta.xml
<CustomField>
    <fullName>Game_Rating__c</fullName>
    <description>Place in Top 10 game rating</description>
    <label>Game Rating</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Game__c/fields/Total_Money_Bet__c.field-meta.xml
<CustomField>
    <fullName>Total_Money_Bet__c</fullName>
    <label>Total Money Bet</label>
    <summarizedField>Bet__c.Amount__c</summarizedField>
    <summaryForeignKey>Bet__c.Game__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/GameTriggerHandler.cls
public class GameTriggerHandler {
    public static void onAfterUpdate(Map<Id, Game__c> oldGamesMap,Map<Id, Game__c> newGamesMap){
        Boolean gamesWithChangedTotalMoneyBet = false;
        for(Game__c game : newGamesMap.values()){
            if(game.Total_Money_Bet__c != oldGamesMap.get(game.Id).Total_Money_Bet__c){
                gamesWithChangedTotalMoneyBet = true;
            }
        }
        if(gamesWithChangedTotalMoneyBet == true){
            recalculateGameRating();
        } 
    }
    private static void recalculateGameRating(){
        List<Game__c> games = [SELECT Id, Total_Money_Bet__c, Game_Rating__c FROM Game__c ORDER BY Total_Money_Bet__c DESC];
        Integer rating = 1;
        for(Game__c game : games){
            game.Game_Rating__c = rating;
            rating++;
            if(rating > 11){
                game.Game_Rating__c = null;
            }
        }
        update games;
    }
}