force-app/main/default/objects/Bet__c/Bet__c.object-meta.xml
<CustomObject>
    <description>Actual bet.</description>
    <label>Bet</label>
    <nameField>
        <displayFormat>BET-{000000}</displayFormat>
        <label>Bet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bet__c/fields/Game__c.field-meta.xml
<CustomField>
    <fullName>Game__c</fullName>
    <label>Game</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Game__c.Start_Date__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Game__c</referenceTo>
    <relationshipLabel>Bets</relationshipLabel>
    <relationshipName>Bets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bet__c/fields/Player__c.field-meta.xml
<CustomField>
    <fullName>Player__c</fullName>
    <label>Player</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Player__c.Total_Money_Won__c</field>
            <operation>greaterOrEqual</operation>
            <value>0</value>
        </filterItems>
        <filterItems>
            <field>Player__c.Total_Money_Won__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Player__c</referenceTo>
    <relationshipLabel>Bets</relationshipLabel>
    <relationshipName>Bets</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Game__c/Game__c.object-meta.xml
<CustomObject>
    <description>Game in totalizator.</description>
    <label>Game</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Game__c/fields/Total_Income__c.field-meta.xml
<CustomField>
    <fullName>Total_Income__c</fullName>
    <description>The total money that was earned by totalizator in this game</description>
    <label>Total Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Player__c/Player__c.object-meta.xml
<CustomObject>
    <description>A person who eagers to win</description>
    <label>Player</label>
    <nameField>
        <displayFormat>PLR-{000000}</displayFormat>
        <label>Player Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Player__c/fields/Total_Money_Won__c.field-meta.xml
<CustomField>
    <fullName>Total_Money_Won__c</fullName>
    <description>All the money player won for all the times.</description>
    <label>Total Money Won</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BetTriggerHandlerTest.cls
@isTest
public class BetTriggerHandlerTest {
    @isTest 
    static void calculateTotalMoneyWonTest(){
        List<Player__c> players = TestDataFactory.createPlayers(1);
       
        List<Game__c> games = TestDataFactory.createGames(10);
        List<Bet__c> bets = new List<Bet__c>();
       
        for(Game__c game : games){
            bets.add(TestDataFactory.createBet(game.Id,players.get(0).Id, 'Won', 1000, false));
        }
        Test.startTest();
        insert bets;
        Test.stopTest();
        List<Player__c> playersAfterCalculate = [SELECT Id,Total_Money_Won__c FROM Player__c];
        System.assert(playersAfterCalculate.get(0).Total_Money_Won__c == 10000, 'The Total_Money_Won__c is incorrect');
        
    }
    
    @isTest 
    static void calculateTotalIncomeTest(){
        List<Player__c> players = TestDataFactory.createPlayers(10);
       
        List<Game__c> games = TestDataFactory.createGames(1);
        List<Bet__c> bets = new List<Bet__c>();
       
        for(Player__c player : players){
            bets.add(TestDataFactory.createBet(games.get(0).Id, player.Id, 'Lost', 500, false));
        }
        Test.startTest();
        insert bets;
        Test.stopTest();
        
        List<Game__c> gamesAfterCalculate = [SELECT Id,Total_Income__c FROM Game__c];
        System.assert(gamesAfterCalculate.get(0).Total_Income__c == 5000, 'The Total_Income__c is incorrect');
        
    }
}