force-app/main/default/objects/Bet__c/Bet__c.object-meta.xml
<CustomObject>
    <description>Actual bet.</description>
    <label>Bet</label>
    <nameField>
        <displayFormat>BET-{000000}</displayFormat>
        <label>Bet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bet__c/fields/Game__c.field-meta.xml
<CustomField>
    <fullName>Game__c</fullName>
    <label>Game</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Game__c.Start_Date__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Game__c</referenceTo>
    <relationshipLabel>Bets</relationshipLabel>
    <relationshipName>Bets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bet__c/fields/Player__c.field-meta.xml
<CustomField>
    <fullName>Player__c</fullName>
    <label>Player</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Player__c.Total_Money_Won__c</field>
            <operation>greaterOrEqual</operation>
            <value>0</value>
        </filterItems>
        <filterItems>
            <field>Player__c.Total_Money_Won__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Player__c</referenceTo>
    <relationshipLabel>Bets</relationshipLabel>
    <relationshipName>Bets</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bet__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Won</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bet__c/fields/Win_Rate__c.field-meta.xml
<CustomField>
    <fullName>Win_Rate__c</fullName>
    <description>Percent indicating how much money Player wins (9 means *1.09)</description>
    <label>Win Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Game__c/Game__c.object-meta.xml
<CustomObject>
    <description>Game in totalizator.</description>
    <label>Game</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Player__c/Player__c.object-meta.xml
<CustomObject>
    <description>A person who eagers to win</description>
    <label>Player</label>
    <nameField>
        <displayFormat>PLR-{000000}</displayFormat>
        <label>Player Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Player__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Actual Player Name</description>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Player__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF( Is_Black_List__c , IMAGE(&quot;https://sandboxcom-a1-dev-ed.file.force.com/sfc/servlet.shepherd/version/renditionDownload?rendition=ORIGINAL_Png&amp;versionId=0687Q000004Y7fr&amp;operationContext=CHATTER&amp;contentId=05T7Q00000IAwMb&quot;,&quot;Bandit&quot;), IF( Total_Money_Won__c &gt; 10000, IMAGE(&quot;https://sandboxcom-a1-dev-ed.file.force.com/sfc/servlet.shepherd/version/renditionDownload?rendition=ORIGINAL_Jpg&amp;versionId=0687Q000004Y7fV&amp;operationContext=CHATTER&amp;contentId=05T7Q00000IAwKu&quot;,&quot;Diamond&quot;),  IF(Total_Money_Won__c &gt; 1000, IMAGE(&quot;https://sandboxcom-a1-dev-ed.file.force.com/sfc/servlet.shepherd/version/renditionDownload?rendition=ORIGINAL_Jpg&amp;versionId=0687Q000004Y7fQ&amp;operationContext=CHATTER&amp;contentId=05T7Q00000IAwKk&quot;,&quot;Star&quot;),  IF(Total_Money_Won__c &lt; 0, IMAGE(&quot;https://sandboxcom-a1-dev-ed.file.force.com/sfc/servlet.shepherd/version/renditionDownload?rendition=ORIGINAL_Jpg&amp;versionId=0687Q000004YEXq&amp;operationContext=CHATTER&amp;contentId=05T7Q00000IBM2L&quot;,&quot;Warning2&quot;), null) )) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TotalizatorDaoTest.cls
@isTest
public class TotalizatorDaoTest {
    /////////////////////SOQLTESTS/////////////////////
    @isTest 
    static void getPlayersTest(){
        TestDataFactory.createPlayers(3);
        
        Test.startTest();
        List<Player__c> players = TotalizatorDao.getPlayers(5, 1);
        Test.stopTest();
        
        System.assert(!players.isEmpty(), 'Method has to return records');
        System.assertEquals(2, players.size(), 'Method has to use LIMIT and OFFSET');
        
    }
    
    @isTest 
    static void getGamesCountTest(){
        TestDataFactory.createGames(3);
        Test.startTest();
        Integer gamesCount = TotalizatorDao.getGamesCount();
        Test.stopTest();
	
        System.assertEquals(3, gamesCount, 'Method has to create games');
    }
    
    @isTest 
    static void getTotalMoneyWonTest(){
        List<Player__c> players = TestDataFactory.createPlayers(2);
        Set<Id> playerIds = new Set<Id>{players.get(0).Id, players.get(1).Id};
       
        Game__c game = TestDataFactory.createGames(1).get(0);
        Bet__c bet1 = TestDataFactory.createBet(game.Id,players.get(0).Id,'Won', 5000, false);
        Bet__c bet2 = TestDataFactory.createBet(game.Id,players.get(1).Id,'Won', 5000, false);
       
        Bet__c bet3 = TestDataFactory.createBet(game.Id,players.get(0).Id,'Won', 10000, false);
        Bet__c bet4 = TestDataFactory.createBet(game.Id,players.get(1).Id,'Lost', 2000, false);
        insert new List<Bet__c>{bet1, bet2, bet3, bet4};
        Test.startTest();
        Map<Id, Decimal> totalMoneyWon = TotalizatorDao.getTotalMoneyWon(playerIds);
        Test.stopTest();
        
        System.assertEquals(15000, totalMoneyWon.get(players.get(0).Id), 'TotalMoneyWon is incorrect');
        System.assertEquals(3000, totalMoneyWon.get(players.get(1).Id), 'TotalMoneyWon is incorrect');
       
    }
    
    @isTest 
    static void getTopPlayersTest(){
        TestDataFactory.createPlayers(5);
        
        Test.startTest();
        List<Player__c> players = TotalizatorDao.getTopPlayers(5, 2);
        Test.stopTest();
        
        System.assert(!players.isEmpty(), 'Method has to return records');
        System.assertEquals(3, players.size(), 'Method has to use LIMIT and OFFSET');
    }
    
    @isTest static void getMostPopularGamesTest(){
        List<Player__c> players = TestDataFactory.createPlayers(1);
       
        List<Game__c> games = TestDataFactory.createGames(3);
        Bet__c bet1 = TestDataFactory.createBet(games.get(0).Id,players.get(0).Id, 'Won', 5000, false);
        Bet__c bet2 = TestDataFactory.createBet(games.get(0).Id,players.get(0).Id, 'Won', 5000, false);
       
        Bet__c bet3 = TestDataFactory.createBet(games.get(1).Id,players.get(0).Id, 'Won', 10000, false);
        Bet__c bet4 = TestDataFactory.createBet(games.get(1).Id,players.get(0).Id, 'Lost', 2000, false);
        insert new List<Bet__c>{bet1, bet2, bet3, bet4};
        
        Test.startTest();
        Map<Id, Integer> popularGames = TotalizatorDao.getMostPopularGames();
        Test.stopTest();
        
        System.assert(!popularGames.isEmpty(), 'Method has to return populated Map');
        System.assertEquals(2, popularGames.get(games.get(0).Id), 'First Game has 2 games');
        System.assertEquals(2, popularGames.get(games.get(1).Id), 'Second Game has 2 games');
        System.assertEquals(0, popularGames.get(games.get(2).Id), 'Third Game has 0 games');
    }
        
      /////////////////////DMLTESTS/////////////////////
      
    @isTest 
    static void createPlayerTest(){
        Test.startTest();
        TotalizatorDao.createPlayer('Yura', 'yura@gmail.com');
        Test.stopTest();
        List<Player__c> players = [SELECT Id,Name__c FROM Player__c];
        System.assertEquals('Yura', players.get(0).Name__c, 'Player should be created and have the correct Name');
    }
    
    @isTest 
    static void updateBetTest(){
        List<Player__c> players = TestDataFactory.createPlayers(2);
        Set<Id> playerIds = new Set<Id>{players.get(0).Id, players.get(1).Id};
       
        Game__c game = TestDataFactory.createGames(1).get(0);
        Bet__c bet = TestDataFactory.createBet(game.Id, players.get(0).Id, 'Won', 5000, true);
        
        Test.startTest();
        TotalizatorDao.updateBet(bet.Id, 3000, 5);
        Test.stopTest();
        
        List<Bet__c> bets = [SELECT Id, Amount__c, Win_Rate__c FROM Bet__c];
        System.assertEquals(3000 , bets.get(0).Amount__c, 'Player amount should be updated');
        System.assertEquals(5 , bets.get(0).Win_Rate__c, 'Player WinRate should be updated');
    }
    
    @isTest 
    static void updateBetWithNullTest(){
        List<Player__c> players = TestDataFactory.createPlayers(2);
        Set<Id> playerIds = new Set<Id>{players.get(0).Id, players.get(1).Id};
       
        Game__c game = TestDataFactory.createGames(1).get(0);
        Bet__c bet = TestDataFactory.createBet(game.Id, players.get(0).Id, 'Won', 5000, true);
        
        Test.startTest();
        TotalizatorDao.updateBet(bet.Id, null, null);
        Test.stopTest();
        
        List<Bet__c> bets = [SELECT Id, Amount__c, Win_Rate__c FROM Bet__c];
        System.assertEquals(5000 , bets.get(0).Amount__c, 'Player amount should NOT be updated');
    }
    
    @isTest static void deleteBetsTest(){
        List<Player__c> players = TestDataFactory.createPlayers(2);
        Set<Id> playerIds = new Set<Id>{players.get(0).Id, players.get(1).Id};
       
        Game__c game = TestDataFactory.createGames(1).get(0);
        Bet__c bet = TestDataFactory.createBet(game.Id, players.get(0).Id, 'Won', 5000, true);
        
        List<Id> betIdsToDelete = new List<Id>{bet.Id};
        
        Test.startTest();
        TotalizatorDao.deleteBets(betIdsToDelete);
        Test.stopTest();
        
        List<Bet__c> bets = [SELECT Id FROM Bet__c];
        System.assert(bets.isEmpty(),'No Bets after delete');
    }
    
    @isTest 
    static void createBetTest(){
        Player__c player = TestDataFactory.createPlayers(1).get(0);
       
        Game__c game = TestDataFactory.createGames(1).get(0);
        Test.startTest();
        TotalizatorDao.createBet(game.Id, player.Id, 15000, 5);
        Test.stopTest();
        List<Bet__c> bets = [SELECT Id,Game__c, Player__c, Status__c FROM Bet__c];
        System.assert(bets.size()>0, 'Bet has to be created');
        System.AssertEquals('Pending', bets.get(0).Status__c, 'Bet Status is incorrect');
    }
    
}