force-app/main/default/objects/Bet__c/Bet__c.object-meta.xml
<CustomObject>
    <description>Actual bet.</description>
    <label>Bet</label>
    <nameField>
        <displayFormat>BET-{000000}</displayFormat>
        <label>Bet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bet__c/fields/Game__c.field-meta.xml
<CustomField>
    <fullName>Game__c</fullName>
    <label>Game</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Game__c.Start_Date__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Game__c</referenceTo>
    <relationshipLabel>Bets</relationshipLabel>
    <relationshipName>Bets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bet__c/fields/Player__c.field-meta.xml
<CustomField>
    <fullName>Player__c</fullName>
    <label>Player</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Player__c.Total_Money_Won__c</field>
            <operation>greaterOrEqual</operation>
            <value>0</value>
        </filterItems>
        <filterItems>
            <field>Player__c.Total_Money_Won__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Player__c</referenceTo>
    <relationshipLabel>Bets</relationshipLabel>
    <relationshipName>Bets</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bet__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Won</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Game__c/Game__c.object-meta.xml
<CustomObject>
    <description>Game in totalizator.</description>
    <label>Game</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Game__c/fields/Total_Income__c.field-meta.xml
<CustomField>
    <fullName>Total_Income__c</fullName>
    <description>The total money that was earned by totalizator in this game</description>
    <label>Total Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Player__c/Player__c.object-meta.xml
<CustomObject>
    <description>A person who eagers to win</description>
    <label>Player</label>
    <nameField>
        <displayFormat>PLR-{000000}</displayFormat>
        <label>Player Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Player__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF( Is_Black_List__c , IMAGE(&quot;https://sandboxcom-a1-dev-ed.file.force.com/sfc/servlet.shepherd/version/renditionDownload?rendition=ORIGINAL_Png&amp;versionId=0687Q000004Y7fr&amp;operationContext=CHATTER&amp;contentId=05T7Q00000IAwMb&quot;,&quot;Bandit&quot;), IF( Total_Money_Won__c &gt; 10000, IMAGE(&quot;https://sandboxcom-a1-dev-ed.file.force.com/sfc/servlet.shepherd/version/renditionDownload?rendition=ORIGINAL_Jpg&amp;versionId=0687Q000004Y7fV&amp;operationContext=CHATTER&amp;contentId=05T7Q00000IAwKu&quot;,&quot;Diamond&quot;),  IF(Total_Money_Won__c &gt; 1000, IMAGE(&quot;https://sandboxcom-a1-dev-ed.file.force.com/sfc/servlet.shepherd/version/renditionDownload?rendition=ORIGINAL_Jpg&amp;versionId=0687Q000004Y7fQ&amp;operationContext=CHATTER&amp;contentId=05T7Q00000IAwKk&quot;,&quot;Star&quot;),  IF(Total_Money_Won__c &lt; 0, IMAGE(&quot;https://sandboxcom-a1-dev-ed.file.force.com/sfc/servlet.shepherd/version/renditionDownload?rendition=ORIGINAL_Jpg&amp;versionId=0687Q000004YEXq&amp;operationContext=CHATTER&amp;contentId=05T7Q00000IBM2L&quot;,&quot;Warning2&quot;), null) )) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Player__c/fields/Total_Money_Won__c.field-meta.xml
<CustomField>
    <fullName>Total_Money_Won__c</fullName>
    <description>All the money player won for all the times.</description>
    <label>Total Money Won</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BetTriggerHandler.cls
public class BetTriggerHandler {
    public static void onAfterInsert(List<Bet__c> newBets){
        calculateTotalMoneyWon(newBets);
        calculateTotalIncome(newBets);
    }
    private static void calculateTotalMoneyWon(List<Bet__c> newBets){
        Set<Id> playerIds = new Set<Id>();
        for(Bet__c bet : newBets){
            playerIds.add(bet.Player__c);
        }
        Map<Id, Decimal> playerIdToTotalMoneyWon = TotalizatorDao.getTotalMoneyWon(playerIds);
        List<Player__c> players = new List<Player__c>();
        for(Id playerId : playerIdToTotalMoneyWon.keySet()){
            Player__c player = new Player__c(Id = playerId,Total_Money_Won__c = playerIdToTotalMoneyWon.get(playerId));
            players.add(player);
        }
        update players;
    }
    private static void calculateTotalIncome(List<Bet__c> newBets){
        Set<Id> gameIds = new Set<Id>();
        for(Bet__c bet : newBets) {
            gameIds.add(bet.Game__c);
        }
        List<Game__c> gamesWithBets = [SELECT Id, (SELECT Amount__c, Status__c FROM Bets__r WHERE Status__c = 'Lost') FROM Game__c WHERE Id IN :gameIds ];
        for(Game__c game : gamesWithBets){
            game.Total_Income__c = 0;
            for(Bet__c bet : game.Bets__r){
                    game.Total_Income__c += bet.Amount__c;
            }
        }
		update gamesWithBets;
    }
}