force-app/main/default/objects/Bet__c/Bet__c.object-meta.xml
<CustomObject>
    <description>Actual bet.</description>
    <label>Bet</label>
    <nameField>
        <displayFormat>BET-{000000}</displayFormat>
        <label>Bet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bet__c/fields/Player__c.field-meta.xml
<CustomField>
    <fullName>Player__c</fullName>
    <label>Player</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Player__c.Total_Money_Won__c</field>
            <operation>greaterOrEqual</operation>
            <value>0</value>
        </filterItems>
        <filterItems>
            <field>Player__c.Total_Money_Won__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Player__c</referenceTo>
    <relationshipLabel>Bets</relationshipLabel>
    <relationshipName>Bets</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Player__c/Player__c.object-meta.xml
<CustomObject>
    <description>A person who eagers to win</description>
    <label>Player</label>
    <nameField>
        <displayFormat>PLR-{000000}</displayFormat>
        <label>Player Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Player__c/fields/Is_Black_List__c.field-meta.xml
<CustomField>
    <fullName>Is_Black_List__c</fullName>
    <defaultValue>false</defaultValue>
    <description>if the User is in the blacklist. No bets are allowed if true.</description>
    <label>Is Black List</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PlayerBonusBatch.cls
public class PlayerBonusBatch implements Database.Batchable<sObject>, Schedulable {
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            'SELECT Id, Name, Bonus__c, (SELECT Id FROM Bets__r WHERE CreatedDate = THIS_MONTH) FROM Player__c WHERE Is_Black_List__c = false'
        );
    }
    
    public void execute(Database.BatchableContext bc, List<Player__c> scope){
        PlayerService.calculatePlayerBonus(scope);
    }
    
    public void finish(Database.BatchableContext bc){
        
    }
    
    public void execute(SchedulableContext ctx) {
        Id batchId = Database.executeBatch(new PlayerBonusBatch());
    }

}