force-app/main/default/objects/Bet__c/Bet__c.object-meta.xml
<CustomObject>
    <description>Actual bet.</description>
    <label>Bet</label>
    <nameField>
        <displayFormat>BET-{000000}</displayFormat>
        <label>Bet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bet__c/fields/Game__c.field-meta.xml
<CustomField>
    <fullName>Game__c</fullName>
    <label>Game</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Game__c.Start_Date__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Game__c</referenceTo>
    <relationshipLabel>Bets</relationshipLabel>
    <relationshipName>Bets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bet__c/fields/Player__c.field-meta.xml
<CustomField>
    <fullName>Player__c</fullName>
    <label>Player</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Player__c.Total_Money_Won__c</field>
            <operation>greaterOrEqual</operation>
            <value>0</value>
        </filterItems>
        <filterItems>
            <field>Player__c.Total_Money_Won__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Player__c</referenceTo>
    <relationshipLabel>Bets</relationshipLabel>
    <relationshipName>Bets</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bet__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Won</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bet__c/fields/Win_Rate__c.field-meta.xml
<CustomField>
    <fullName>Win_Rate__c</fullName>
    <description>Percent indicating how much money Player wins (9 means *1.09)</description>
    <label>Win Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Game__c/Game__c.object-meta.xml
<CustomObject>
    <description>Game in totalizator.</description>
    <label>Game</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Player__c/Player__c.object-meta.xml
<CustomObject>
    <description>A person who eagers to win</description>
    <label>Player</label>
    <nameField>
        <displayFormat>PLR-{000000}</displayFormat>
        <label>Player Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Player__c/fields/Is_Black_List__c.field-meta.xml
<CustomField>
    <fullName>Is_Black_List__c</fullName>
    <defaultValue>false</defaultValue>
    <description>if the User is in the blacklist. No bets are allowed if true.</description>
    <label>Is Black List</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Player__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Actual Player Name</description>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Player__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF( Is_Black_List__c , IMAGE(&quot;https://sandboxcom-a1-dev-ed.file.force.com/sfc/servlet.shepherd/version/renditionDownload?rendition=ORIGINAL_Png&amp;versionId=0687Q000004Y7fr&amp;operationContext=CHATTER&amp;contentId=05T7Q00000IAwMb&quot;,&quot;Bandit&quot;), IF( Total_Money_Won__c &gt; 10000, IMAGE(&quot;https://sandboxcom-a1-dev-ed.file.force.com/sfc/servlet.shepherd/version/renditionDownload?rendition=ORIGINAL_Jpg&amp;versionId=0687Q000004Y7fV&amp;operationContext=CHATTER&amp;contentId=05T7Q00000IAwKu&quot;,&quot;Diamond&quot;),  IF(Total_Money_Won__c &gt; 1000, IMAGE(&quot;https://sandboxcom-a1-dev-ed.file.force.com/sfc/servlet.shepherd/version/renditionDownload?rendition=ORIGINAL_Jpg&amp;versionId=0687Q000004Y7fQ&amp;operationContext=CHATTER&amp;contentId=05T7Q00000IAwKk&quot;,&quot;Star&quot;),  IF(Total_Money_Won__c &lt; 0, IMAGE(&quot;https://sandboxcom-a1-dev-ed.file.force.com/sfc/servlet.shepherd/version/renditionDownload?rendition=ORIGINAL_Jpg&amp;versionId=0687Q000004YEXq&amp;operationContext=CHATTER&amp;contentId=05T7Q00000IBM2L&quot;,&quot;Warning2&quot;), null) )) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Player__c/fields/Total_Money_Won__c.field-meta.xml
<CustomField>
    <fullName>Total_Money_Won__c</fullName>
    <description>All the money player won for all the times.</description>
    <label>Total Money Won</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TotalizatorDao.cls
//-------------------SOQL-------------------//
public class TotalizatorDao {
    public static List<Player__c> getPlayers(Integer limitNumber, Integer offset){
        return [SELECT Id, Name, Name__c FROM Player__c WHERE Is_Black_List__c = false LIMIT :limitNumber OFFSET :offset];
    }
    
    public static  List<AggregateResult> getGamesCount(){
        List<AggregateResult> countGames = [SELECT COUNT(Id) FROM Game__c];
        return countGames;
    }
    
    public static  Integer getGamesCount2(){
        Integer countGames = [SELECT COUNT() FROM Game__c];
        return countGames;
    }
    
    public static Map<Id, Decimal> getTotalMoneyWon(Set<Id> playerIds){
        Map<Id, Decimal> playerIdToTotalMoneyWon = new Map<Id, Decimal>();
        Decimal amountForPlayer;

        for(Player__c player : [SELECT Id, (SELECT Amount__c, Status__c FROM Bets__r) FROM Player__c WHERE Id IN :playerIds]){
        	 amountForPlayer = 0;
            for(Bet__c bet : player.Bets__r){
                if (bet.Status__c == 'Won'){
                    amountForPlayer += bet.Amount__c;
                } else if (bet.Status__c == 'Lost'){
                    amountForPlayer -= bet.Amount__c;
                }
            }
            playerIdToTotalMoneyWon.put(player.Id, amountForPlayer);
            
        }
        return playerIdToTotalMoneyWon;
    }
    
    public static List<Player__c> getTopPlayers(Integer limitNumber, Integer offset){
        return [SELECT Name, Name__c, Total_Money_Won__c FROM Player__c ORDER BY Total_Money_Won__c DESC LIMIT :limitNumber OFFSET :offset];
    }

    public static Map<Id, Integer> getMostPopularGames(){
        Map<Id, Integer> popularGames = new Map<Id, Integer>();

        for(Game__c game : [SELECT Id, (SELECT Id FROM Bets__r) FROM Game__c]){
            popularGames.put(game.Id, game.Bets__r.size());
        }     
        return popularGames;
    }
    public static void createPlayer(String playerName, String playerEmail){
        Player__c player = new Player__c(Name__c = playerName,Email__c = playerEmail);
         Database.insert(player);
     }
     public static void updateBet(Id betId, Decimal amount, Decimal percent){
         if ( (amount != null) || (percent != null) ){
             Bet__c bet = new Bet__c(Id = betId);
             if (amount != null){
                 bet.Amount__c = amount;
             }
             if(percent != null){
                 bet.Win_Rate__c = percent;
             }
             Database.update(bet);
         }
     }
     public static void deleteBets(List<Id> betIds){
         Database.delete(betIds);
     }
     public static void createBet(Id game, Id player, Decimal amount, Decimal winRate){
         Bet__c bet = new Bet__c(Game__c = game, Player__c = player, Amount__c = amount, Win_Rate__c = winRate, Status__c = 'Pending');
         Database.insert(bet);
     }
}